/* Auto-generated by genmsg_cpp for file /home/caveman/ros_workspace/flybot/optic_flow/msg/FloatArray.msg */
#ifndef OPTIC_FLOW_MESSAGE_FLOATARRAY_H
#define OPTIC_FLOW_MESSAGE_FLOATARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace optic_flow
{
template <class ContainerAllocator>
struct FloatArray_ {
  typedef FloatArray_<ContainerAllocator> Type;

  FloatArray_()
  : shape()
  , data()
  {
  }

  FloatArray_(const ContainerAllocator& _alloc)
  : shape(_alloc)
  , data(_alloc)
  {
  }

  typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _shape_type;
  std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  shape;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  data;


  typedef boost::shared_ptr< ::optic_flow::FloatArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optic_flow::FloatArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FloatArray
typedef  ::optic_flow::FloatArray_<std::allocator<void> > FloatArray;

typedef boost::shared_ptr< ::optic_flow::FloatArray> FloatArrayPtr;
typedef boost::shared_ptr< ::optic_flow::FloatArray const> FloatArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::optic_flow::FloatArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::optic_flow::FloatArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace optic_flow

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::optic_flow::FloatArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::optic_flow::FloatArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::optic_flow::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b44a887daa94a23c9a22247bea6d0b5d";
  }

  static const char* value(const  ::optic_flow::FloatArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb44a887daa94a23cULL;
  static const uint64_t static_value2 = 0x9a22247bea6d0b5dULL;
};

template<class ContainerAllocator>
struct DataType< ::optic_flow::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "optic_flow/FloatArray";
  }

  static const char* value(const  ::optic_flow::FloatArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::optic_flow::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16[] shape\n\
float32[] data\n\
\n\
";
  }

  static const char* value(const  ::optic_flow::FloatArray_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::optic_flow::FloatArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.shape);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FloatArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optic_flow::FloatArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::optic_flow::FloatArray_<ContainerAllocator> & v) 
  {
    s << indent << "shape[]" << std::endl;
    for (size_t i = 0; i < v.shape.size(); ++i)
    {
      s << indent << "  shape[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.shape[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // OPTIC_FLOW_MESSAGE_FLOATARRAY_H

